### ISSUE TITLE
Trouble with running source function in Lab 1

### ISSUE THREAD

**Issue by MJJMayor** [jbryer/DATA606Fall2019#2]
I started looking at Lab 1 and tried to start with the first code it says to input "source("more/arbuthnot.R")", but I am getting this error message: "Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'more/arbuthnot.R': No such file or directory"

I have installed the packages with the code from the course site.  I even tried loading the openintro library.
I'm sorry if I am missing something obvious here, I feel a bit embarrassed encountering a problem with literally the first line of code required for this course.

**Comment by SieSiongWong** [comment]
Hi MJ, how do you resolve this issue as I'm getting the same error?

**Comment by MJJMayor** [comment]
I was able to solve the problem by follow the instructions on this page:
data606.net/post/2019-08-27-getting-started-with-r/

I think my issue was that I just needed to run "library(DATA606)" and then
"startLab('Lab1')" before starting the lab.

**Comment by SieSiongWong** [comment]
Thanks a lot. It helps. 

There are just so much information to digest and to get familiar with at the beginning for both 606 and 607.
